{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aws-container-insight-fluent-bit.serviceAccountName" . }}
  namespace: {{ include "aws-container-insight-fluent-bit.namespace" . }}
  labels:
    {{- include "aws-container-insight-fluent-bit.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
